"""Train the ResuMatch ranker on synthetic/heuristic-labeled data.

NOTE: Labels are generated by a deterministic heuristic, not real hiring
outcomes. The model learns the heuristic and is a reproducible starting
point, not a validated predictor of real-world fit.

Run:  python -m scripts.train   (from backend/)
"""
import sys
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from resumatch.ranker import Ranker  # noqa: E402

_OUT = Path(__file__).resolve().parent.parent / "ranker.joblib"


def synth_label(sim: float, overlap: float, exp: float) -> int:
    """Heuristic ground truth: weighted score above threshold == good fit."""
    score = 0.5 * sim + 0.35 * overlap + 0.15 * exp
    return int(score >= 0.5)


def build_dataset(n: int = 4000, seed: int = 42):
    rng = np.random.default_rng(seed)
    sim = rng.beta(2, 2, n)
    overlap = rng.beta(1.5, 1.5, n)
    exp = rng.beta(2, 3, n)
    X = np.column_stack([sim, overlap, exp])
    base = 0.5 * sim + 0.35 * overlap + 0.15 * exp
    noisy = base + rng.normal(0, 0.05, n)
    y = (noisy >= 0.5).astype(int)
    return X, y


def train_model(n: int = 4000, seed: int = 42, out_path: str = str(_OUT)):
    X, y = build_dataset(n=n, seed=seed)
    X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size=0.25, random_state=seed)
    clf = LogisticRegression(max_iter=1000).fit(X_tr, y_tr)
    proba = clf.predict_proba(X_te)[:, 1]
    metrics = {"roc_auc": float(roc_auc_score(y_te, proba))}
    ranker = Ranker(clf)
    ranker.save(out_path)
    return ranker, metrics


if __name__ == "__main__":
    _, metrics = train_model()
    print(f"Trained ranker -> {_OUT}")
    print(f"ROC-AUC (held-out): {metrics['roc_auc']:.3f}")
